"""add summary column

Revision ID: 6cc3fb1ccd30
Revises: 
Create Date: 2020-02-29 20:04:30.151718

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6cc3fb1ccd30'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('pilkanoznapl', sa.Column('summary', sa.TEXT(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('pilkanoznapl', 'summary')
    # ### end Alembic commands ###
