"""add source column

Revision ID: f4c188e53f88
Revises: 80638c5c4a78
Create Date: 2020-03-06 23:49:53.352361

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f4c188e53f88'
down_revision = '80638c5c4a78'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('pilkanoznapl', sa.Column('source', sa.String(length=50), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('pilkanoznapl', 'source')
    # ### end Alembic commands ###
